name: Upload Go test results

on: [push]

permissions:
  contents: write

jobs:
  Test ccwc package:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: Install dependencies
        run: go get .
      - name: Test with Go
        run: go test

      # - name: Upload Go test results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Go-results
      #     path: TestResults.json
